{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-1.0.aar",
          "url": "sqflite_release-1.0.aar",
          "size": 44672,
          "sha512": "04468a3e87a69c2bb58c9d7f3f84770ee56a0a3b3b58b4f929ec251aa0e0688b7962081dea1bee26547d52cf068f94760a0557da59d5f4d5b4e3a50885f77159",
          "sha256": "87c6da63a9285ed7ef43d2f8b7faea7b08133e9f1ca1ca84379f290eabeaba16",
          "sha1": "9380c7a108c2193361b81e0568646d91f0b54a76",
          "md5": "e64df089c58e0051d8dab5031526871c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-1.0.aar",
          "url": "sqflite_release-1.0.aar",
          "size": 44672,
          "sha512": "04468a3e87a69c2bb58c9d7f3f84770ee56a0a3b3b58b4f929ec251aa0e0688b7962081dea1bee26547d52cf068f94760a0557da59d5f4d5b4e3a50885f77159",
          "sha256": "87c6da63a9285ed7ef43d2f8b7faea7b08133e9f1ca1ca84379f290eabeaba16",
          "sha1": "9380c7a108c2193361b81e0568646d91f0b54a76",
          "md5": "e64df089c58e0051d8dab5031526871c"
        }
      ]
    }
  ]
}
