{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.non_casa_product_list",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 17817580,
          "sha512": "51ac5a5097ff081b47954fd92f06f4d08eeba37d4fcb570da8f9ae0b64f3935a79ea4d38c89efc4d6007c320ec13f5657ab53209431043b3fcb6ddb535acaee6",
          "sha256": "9f833c4254f1374d99a51bc2dd690f5524e82b71263ea47a205ff534a69bf4cf",
          "sha1": "3352fc52ef865eda4083052cfd8263c17d1a879d",
          "md5": "7512aeef60e5ae62c9ab156bad907233"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-1837b5be5f0f1376a1ccf383950e83a80177fb4e"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 17817580,
          "sha512": "51ac5a5097ff081b47954fd92f06f4d08eeba37d4fcb570da8f9ae0b64f3935a79ea4d38c89efc4d6007c320ec13f5657ab53209431043b3fcb6ddb535acaee6",
          "sha256": "9f833c4254f1374d99a51bc2dd690f5524e82b71263ea47a205ff534a69bf4cf",
          "sha1": "3352fc52ef865eda4083052cfd8263c17d1a879d",
          "md5": "7512aeef60e5ae62c9ab156bad907233"
        }
      ]
    }
  ]
}
